# Generated by Django 5.0.6 on 2024-07-09 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Model_No', models.CharField(max_length=100)),
                ('Type_of_Material', models.CharField(max_length=100)),
                ('Supplier_Name', models.CharField(max_length=100)),
                ('Weight_of_Material', models.FloatField()),
                ('Percentage_Composition', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='evusage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Model_No', models.CharField(max_length=100)),
                ('Vehicle_ID', models.CharField(max_length=100)),
                ('Owner_Name', models.CharField(max_length=100)),
                ('Sold_Date', models.DateField()),
                ('Daily_Operational_KM', models.IntegerField()),
                ('Total_KM_Operation', models.IntegerField()),
                ('Source_of_Power', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
