# Generated by Django 5.0.6 on 2024-07-02 08:38

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default=None, upload_to='Resource')),
                ('Title', models.CharField(max_length=20)),
                ('Description', tinymce.models.HTMLField(max_length=2000)),
                ('Highlight', models.CharField(max_length=50)),
            ],
        ),
    ]
