# Generated by Django 5.0.6 on 2024-07-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='Highlight',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='resource',
            name='Title',
            field=models.CharField(max_length=40),
        ),
    ]
