# Generated by Django 5.0.6 on 2024-07-02 08:41

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0002_alter_resource_highlight_alter_resource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='Description',
            field=tinymce.models.HTMLField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='resource',
            name='Highlight',
            field=models.CharField(max_length=350),
        ),
    ]
